# Numpy
kita akan belajar menggunakan package Numpy di Python

 - Tipe data Numpy Array
  - CRUD create read update delete sebuah numpy array
 - cara kalkulasi angka menggunakan Numpy

In [1]:
# semua package yang kita gunakan biasakan di import di satu tempat saja di notebook, di awal
import numpy as np

In [2]:
print([1,2,3,4])

[1, 2, 3, 4]


In [3]:
print(np.array([1,2,3,4]))

[1 2 3 4]


In [4]:
print(np.array([[1,2],[3,4]]))

[[1 2]
 [3 4]]


cara mudah untuk membuat numpy array adalah dengan np.array()

di dalam function np.array() tersebut kita isi dengan list angka

dengan begitu kita akan dapat (hasil return) sebuah numpy array

In [5]:
a = np.array([1,2,3])

print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


selain menggunakan sebuah list isi angka yang kita pass sebagai argumen ke function `np.array()` masih ada banyak cara lain untuk membuat sebuah numpy array:

1. numpy array isi angka 0 semua, `np.zeros()`
2. isi angka 1 semua, `np.ones()`
3. isi angka random, `np.random.random()`
4. isi kosong, kita tidak peduli isinya apa, `np.empty()`
5. isi angka urut, cara tulisnya seperti saat kita bikin range, `np.arange()`

In [6]:
# numpy zeros, kita isi satu int atau tuple isi int untuk menandakan berapa banyak angka 0 yang kita mau di np array ini
b = np.zeros(10)

print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
print(type(b))

<class 'numpy.ndarray'>


kita akan paling sering memanipulasi data 2 dimensi, data tabular, ada kolom ada baris.

kita akan membuat np array 2 dimensi dengan memberi tau pakai tuple, "shape" nya, bentuk dari numpy array ini

ada berapa baris, ada berapa kolom. ada berapa item di dimensi ke-1 dan ada berapa item di dimensi ke-2.

In [8]:
b2 = np.zeros((3,4))

print(b2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# ones
c = np.ones(8)
c2 = np.ones((2, 6))

print(c)
print(c2)

[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [13]:
# random
d = np.random.random(8)
d2 = np.random.random((2, 6))

print(d)
print(d2)

[0.72883316 0.97118143 0.70641272 0.55423304 0.32707849 0.78207457
 0.42579818 0.59847518]
[[0.04067977 0.501135   0.1327426  0.06722066 0.26730664 0.28630068]
 [0.31446842 0.44514548 0.36805876 0.45557482 0.96358055 0.58826154]]


kenapa random 2 kali random.random? karena sebenarnya ada banyak cara untuk generate random numbers, bisa juga kita minta random.randint khusus integer, random.rand, random.... masi banyak lainnya.

kali ini kita fokus ke 1 dulu saja, random.random

In [15]:
# empty
# isi np.empty kita tidak peduli, bisa 0 semua, 1 semua, random, atau angka lainnya

e = np.empty(3)
e2 = np.empty((5, 2))

print(e)
print(e2)

[1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


untuk np.arange, cara isinya sedikit berbeda dengan yang lain. karena dia lebih mirip cara isi range

In [16]:
# np.arange()

r = np.arange(5)
print(r)

[0 1 2 3 4]


In [17]:
r = np.arange(5, 20)
print(r)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
r = np.arange(5, 20, 7)
print(r)

[ 5 12 19]


kita sudah pelajari cara membuat numpy array
- numpy array 1 dimensi
- numpy array 2 dimensi
- numpy array yang isinya tergantung list kita isi apa
- 0 semua
- 1 semua
- random
- tidak peduli isi, bentuk saja
- angka urut

berikutnya kita pelajari cara baca sebuah numpy array.

selain untuk membaca angka di posisi tertentu di sebuah numpy array, kita juga bisa minta informasi tentang numpy array tersebut:
- shape, ada berapa dimensi numpy array ini? berapa baris, berapa kolom?
- ndim, ada berapa dimensi
- size, jumlah item, ada berapa angka di dalam numpy array ini?

In [21]:
# misalakan kita mau cek numpy array b, dan b2

print(b)
print(b.shape)
print(b.ndim)
print(b.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
1
10


b adalah sebuah numpy array berisi angka 0

shape menunjukkan bentuknya (10,) ada 10 item di dimensi pertama

ndim menunjukkan dimensinya 1, bahwa b adalah numpy array 1 dimensi

size menunjukkan 10, ada 10 angka di dalam numpy array b

In [22]:
print(len(b))

10


size bisa juga digantikan function bawaan python, len, untuk menghitung ada berapa item di dalam array/ list/ string tersebut.

In [24]:
print(b2)
print(b2.shape)
print(b2.ndim)
print(b2.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
2
12


disini karena b2 adalah sebuah numpy array 2 dimensi, kita bisa lihat kalau:
- shape memiliki 2 angka, (3,4), ada 3 item di dimensi pertama, 3 kali [0,0,0,0]. lalu ada 4 item di dimensi kedua, ada 4 angka 0 di dalam sebuah item dimensi pertama.
- ndim bilang 2, untuk 2 dimensi
- size bilang 12, ada 12 angka 0 di dalam array b2

### n-dimensional array
sebenarnya numpy array bisa lebih dari 2 dimensi. dia bisa memiliki 1,2,3,4,5,.... unlimited dimensi. python bisa handle hal tersebut.

hanya di dunia riil, biasanya kita paling sering handle data di 2 dimensi. jadi contoh contoh di kelas kedepannya hampir semuanya di 2 dimensi.

In [26]:
# contoh data 3 dimensi
b3 = np.ones((2,3,5))
print(b3)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### append delete sort


In [29]:
arr_urut = np.array([1,2,3,4,5,6])

print(arr_urut)

[1 2 3 4 5 6]


In [31]:
arr_baru = np.append(arr_urut, 7)

print(arr_baru)

[1 2 3 4 5 6 7]


In [32]:
print(arr_urut)

[1 2 3 4 5 6]


In [34]:
# append
arr_baru = np.append(arr_urut, [[7,8],[10,12]])

print(arr_baru)

[ 1  2  3  4  5  6  7  8 10 12]


In [35]:
# delete
arr_baru = np.delete(arr_urut, [0,2])

print(arr_baru)

[2 4 5 6]


In [36]:
# sort
arr_berantakan = np.array([456,234,-23,54,87,2,-1238])

print(arr_berantakan)

arr_sorted = np.sort(arr_berantakan)

print(arr_sorted)

[  456   234   -23    54    87     2 -1238]
[-1238   -23     2    54    87   234   456]


## Reshape
kita bisa mengubah shape sebuah numpy array

dengan catatan size sebelum dan sesudah di reshape sama.

misalakan numpy array shape (2,3) berarti ada 6 angka di dalam numpy array tersebut, size 6, kita bisa reshape menjadi (3,2), menjadi (6,1), menjadi (1,6), atau (6,) satu dimensi isi 6 angka.

In [39]:
arr_new = np.arange(6)

print(arr_new)
print(arr_new.shape, "shape array arr_new")

[0 1 2 3 4 5]
(6,) shape array arr_new


In [40]:
arr_reshaped = arr_new.reshape((2,3))
print(arr_reshaped, "di reshape menjadi (2,3) 2 dimensi dengan 2 baris 3 kolom")

[[0 1 2]
 [3 4 5]] di reshape menjadi (2,3) 2 dimensi dengan 2 baris 3 kolom


In [41]:
arr_reshaped = arr_new.reshape((3,2))
print(arr_reshaped, arr_reshaped.shape)

arr_reshaped = arr_new.reshape((6,1))
print(arr_reshaped, arr_reshaped.shape)

arr_reshaped = arr_new.reshape((1,6))
print(arr_reshaped, arr_reshaped.shape)

arr_reshaped = arr_new.reshape((3,2,1))
print(arr_reshaped, arr_reshaped.shape)

[[0 1]
 [2 3]
 [4 5]] (3, 2)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)
[[0 1 2 3 4 5]] (1, 6)
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]] (3, 2, 1)


# Indexing dan Slicing
indexing: mengambil 1 angka dari sebuah numpy array   
slicing: mengambil beberapa angka dari sebuah numpy array

In [48]:
arr_contoh = np.arange(12)
arr_contoh = arr_contoh.reshape((3,4))

# arr_contoh = np.arange(12).reshape((3,4))

print(arr_contoh)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
# kita coba ambil angka 6, indexing
# angka 6 ada di posisi baris ke2, kolom ke3

# baris ke 2 memiliki index 1, karena index dimulai dari 0
# kolom ke 3 memiliki index 2, karena index dimulai dari 0, 1, 2, 3, ...
print(arr_contoh[1, 2])

6


untuk numpy array 1 dimensi, kita cuma perlu 1 index

In [50]:
arr_contoh1 = np.arange(12)
print(arr_contoh1)
print(arr_contoh1[6])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
6


In [52]:
arr_contoh2 = np.arange(1, 12)
print(arr_contoh2)
print(arr_contoh2[6])

[ 1  2  3  4  5  6  7  8  9 10 11]
7


In [53]:
arr_contoh2 = np.random.random(12)
print(arr_contoh2)
print(arr_contoh2[6])

[0.0292552  0.90916371 0.54851109 0.54808263 0.04890998 0.27162037
 0.22834078 0.14499318 0.75421001 0.43394406 0.68932551 0.20060395]
0.2283407805166925


untuk slicing, kita mau ambil beberapa angka sekaligus

In [51]:
print(arr_contoh)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [61]:
# misalkan kita mau ambil angka 1,2,5,6
# angka 1,2,5,6 ada di... baris ke1 dan ke2, kolom ke2 dan ke3

# baris 1,2 memiliki index 0,1, untuk ambil semuanya antara index 0 dan 1, kita pakai :, tapi mirip range, angka terakhir perlu di +1
# baris 0:2
# baris index 0 sampai index 1 diambil semua

# kolom 2,3 memiliki index 1,2
# kolom 1:3
# kolom index 1 sampai index 2 diambil semua

print(arr_contoh[0:2, 1:3])

[[1 2]
 [5 6]]


cobalah ambil slicing array arr_contoh untuk angka 2,6,10

In [62]:
arr_contoh = np.arange(12).reshape((3,4))
print(arr_contoh)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [63]:
# semua baris
# kolom k3, kolom index 2

print(arr_contoh[:, 2])

[ 2  6 10]


In [64]:
print(arr_contoh[:, [2]])

[[ 2]
 [ 6]
 [10]]


In [65]:
hasil = arr_contoh[:, 2].reshape((3,1))
print(hasil)

[[ 2]
 [ 6]
 [10]]


## kalkulasi
sejauh ini semua yang sudah kita lakukan adalah CRUD numpy array, kita bikin, edit, baca informasi, ambil data tertentu dengan indexing/ slicing, delete, sortir

tapi sebenarnya numpy dibuat untuk kalkukasi matematik di python

berbeda dengan list, angka2 yang ada di numpy array bisa dengan mudah kita ubah pakai operator matematika

bisa juga kita +-*/ dengan numpy array lainnya

bisa juga kita gunakan fungsi bawaan numpy untuk agregasi, seperti cari rata-rata, max, min, dan angka statistik lainnya

In [67]:
a = np.ones(24)

print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [68]:
# broadcasting, melakukan operasi matematik antara 1 numpy array dengan 1 angka
b = a * 3
print(b)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [69]:
# melakukan operasi matematik antara 2 numpy array yang mempunyai ukuran yang sama
c = a + b
print(c)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


In [70]:
d = a + b * c / 10
print(d)

[2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2
 2.2 2.2 2.2 2.2 2.2 2.2]


In [71]:
a2 = a.reshape((3,8))
print(a2)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [73]:
b2 = a2 * 10 / 2
print(b2)

[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]


In [74]:
c2 = a2 + b2 * b2
print(c2)

[[26. 26. 26. 26. 26. 26. 26. 26.]
 [26. 26. 26. 26. 26. 26. 26. 26.]
 [26. 26. 26. 26. 26. 26. 26. 26.]]


In [77]:
# misalkan kita mau generate data random hasil buang dadu
# 1,2,3,4,5,6 adalah hasil buang dadu
# gimana kalau kita buat data hasil buang dadu 100x?

dadu100 = np.random.random(100) * 5 + 1
dadu100 = np.round(dadu100)
print(dadu100)

[3. 4. 6. 2. 5. 3. 4. 3. 5. 2. 4. 2. 4. 5. 5. 4. 5. 3. 2. 2. 4. 6. 4. 5.
 2. 4. 3. 5. 2. 6. 6. 1. 3. 4. 3. 3. 4. 2. 5. 4. 5. 3. 3. 3. 4. 2. 6. 5.
 1. 2. 2. 6. 2. 3. 2. 2. 3. 6. 4. 6. 4. 5. 3. 3. 3. 3. 5. 5. 6. 2. 2. 4.
 5. 5. 1. 2. 5. 2. 3. 5. 1. 5. 6. 2. 5. 3. 6. 5. 5. 2. 1. 4. 4. 5. 2. 3.
 3. 4. 1. 4.]


In [80]:
# cek min, max, mean, median
print("min", np.min(dadu100))
print("max", np.max(dadu100))
print("mean", np.mean(dadu100))
print("median", np.median(dadu100))

min 1.0
max 6.0
mean 3.63
median 4.0


In [81]:
# misalkan ada 2 numpy array size sama, tapi shape beda

a = np.array([3,5,7,8])
b = np.array([[1,3],[5,0]])

print(a, a.shape, a.size)
print(b, b.shape, b.size)

[3 5 7 8] (4,) 4
[[1 3]
 [5 0]] (2, 2) 4


In [85]:
c = a.reshape((2,2))
print(c)

[[3 5]
 [7 8]]


In [87]:
d = c * b
print(d)

[[ 3 15]
 [35  0]]


stacking dan splitting

stack: menempelkasn beberapa numpy array jadi satu

split: memisahkan 1 numpy array menjadi beberapa bagian yang size sama

In [92]:
# horizontal stack, ditempelnya kiri ke kanan
e = np.hstack((c, d, b))
print(e)

[[ 3  5  3 15  1  3]
 [ 7  8 35  0  5  0]]


In [91]:
# vertical stack, ditempelnya atas ke bawah
f = np.vstack((c, d, b))
print(f)

[[ 3  5]
 [ 7  8]
 [ 3 15]
 [35  0]
 [ 1  3]
 [ 5  0]]


In [94]:
# horizontal split
np.hsplit(e, 2)

[array([[ 3,  5,  3],
        [ 7,  8, 35]]),
 array([[15,  1,  3],
        [ 0,  5,  0]])]

In [96]:
# vertical split
np.vsplit(f, 2)

[array([[ 3,  5],
        [ 7,  8],
        [ 3, 15]]),
 array([[35,  0],
        [ 1,  3],
        [ 5,  0]])]

function, untuk di "invoke" di jalankan, kita pakai ()   
- nama_function()
- nama_function(arg1, arg2, ...)

untuk data yang bersifat tuple, kita pakai () juga, () juga digunakan untuk membuat tuple. Untuk function numpy yang shape dan reshape, dia memberi dan menerima bentuk numpy array sebagai tuple.


In [98]:
print(a)
print(a.shape)

[3 5 7 8]
(4,)


In [99]:
# function reshape
a.reshape

<function ndarray.reshape>

In [101]:
# jalanin function pakai () untuk di invoke
# kebetulan, argumen reshape harus dalam bentuk tuple, tuple dibuat dengan ()
a.reshape((4,1))

array([[3],
       [5],
       [7],
       [8]])

In [102]:
# sebuah list dibuat dengan []
# function numpy array, kita invoke pakai () dan dia menerima argumen sebuah list []
np.array([])

array([], dtype=float64)

In [103]:
# index, dan key, untuk akses data, untuk indexing, untuk slicing, juga menggunakan []
print(dadu100)

[3. 4. 6. 2. 5. 3. 4. 3. 5. 2. 4. 2. 4. 5. 5. 4. 5. 3. 2. 2. 4. 6. 4. 5.
 2. 4. 3. 5. 2. 6. 6. 1. 3. 4. 3. 3. 4. 2. 5. 4. 5. 3. 3. 3. 4. 2. 6. 5.
 1. 2. 2. 6. 2. 3. 2. 2. 3. 6. 4. 6. 4. 5. 3. 3. 3. 3. 5. 5. 6. 2. 2. 4.
 5. 5. 1. 2. 5. 2. 3. 5. 1. 5. 6. 2. 5. 3. 6. 5. 5. 2. 1. 4. 4. 5. 2. 3.
 3. 4. 1. 4.]


In [104]:
# ambil hasil lempar dadu yang ke 10
# angka ke10, berarti index 9
# data[index]
dadu100[9]

2.0

In [105]:
# slicing juga pakai index, jadi pakai [] untuk data
# data[index]
# bedanya slicing, index bisa banyak, kalau ada lebih dari 1 index, kita bisa pakai list berisi index index
# list dibuat menggunakan []

# misalkan kita mau ambil hasil lempar dadu ke 10 dan ke 20
# index ke 9 dan ke 19, ada lebih dari 1 index, kita bisa kumpulin ke 1 list --> [9, 19]
dadu100[[9, 19]]

array([2., 2.])

In [107]:
# misalkan kita mau ambil hasil lempar dadu k1, ke-10 dan terakhir
# index 0, index 9, dan index -1 --> [0, 9, -1]

dadu100[[0, 9, -1]]

array([3., 2., 4.])

# matrices, transpose, dot product
matrices: numpy array 2 dimensi

transpose: mengubah shape sebuah matrix sambil memastikan teman sebaris menjadi teman sekolom

dot product: perkalian spesial antara dua matrix

In [108]:
arr_penjualan = np.array([
                            [5,	10,	15],
                            [6,	8,	7]
                         ])

print(arr_penjualan)

[[ 5 10 15]
 [ 6  8  7]]


In [109]:
# transpose
print(arr_penjualan.T)

[[ 5  6]
 [10  8]
 [15  7]]


tipe data numpy array, memiliki beberapa sifat yang bisa kita panggil: shape, ndim, size, T

In [110]:
print(arr_penjualan.T.T)

[[ 5 10 15]
 [ 6  8  7]]


In [111]:
# reshape
print(arr_penjualan.reshape((3,2)))

[[ 5 10]
 [15  6]
 [ 8  7]]


untuk contoh dot product, sample data dibuat di [google sheets ini](https://docs.google.com/spreadsheets/d/1mMTuWh5zPnzCdueICh_EVEK96VIpNx1vR6CZdiG_I44/edit?usp=sharing)

In [112]:
# dot product
p = arr_penjualan.T
print(p)

[[ 5  6]
 [10  8]
 [15  7]]


In [113]:
harga = np.array([[5000],
                  [1500]])
print(harga)

[[5000]
 [1500]]


In [115]:
hasil = p.dot(harga)
print(hasil)

[[34000]
 [62000]
 [85500]]


total harga penjualan senin 34000, selasa 62000, rabu 85500

kalau mau di total, kita bisa pakai numpy array function sum

In [116]:
np.sum(hasil)

181500